## This configuration was generated by terraform-provider-oci

resource oci_core_subnet export_terraform-subnet {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/30"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ociuser"
    "Oracle-Tags.CreatedOn" = "2022-03-21T13:15:42.011Z"
  }
  dhcp_options_id = oci_core_vcn.export_terraform-vcn.default_dhcp_options_id
  display_name    = "terraform-subnet"
  #dns_label = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_terraform-vcn.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_terraform-vcn.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_terraform-vcn.id
}

resource oci_core_vcn export_terraform-vcn {
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/29",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ociuser"
    "Oracle-Tags.CreatedOn" = "2022-03-21T13:15:41.259Z"
  }
  display_name = "terraform-vcn"
  #dns_label = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #is_ipv6enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-terraform-vcn {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ociuser"
    "Oracle-Tags.CreatedOn" = "2022-03-21T13:15:41.259Z"
  }
  display_name     = "Default DHCP Options for terraform-vcn"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_terraform-vcn.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
}

resource oci_core_default_route_table export_Default-Route-Table-for-terraform-vcn {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ociuser"
    "Oracle-Tags.CreatedOn" = "2022-03-21T13:15:41.259Z"
  }
  display_name = "Default Route Table for terraform-vcn"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_terraform-vcn.default_route_table_id
}

resource oci_core_default_security_list export_Default-Security-List-for-terraform-vcn {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ociuser"
    "Oracle-Tags.CreatedOn" = "2022-03-21T13:15:41.259Z"
  }
  display_name = "Default Security List for terraform-vcn"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/29"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_terraform-vcn.default_security_list_id
}

