## This configuration was generated by terraform-provider-oci

resource oci_devops_project export_oci-github-access {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ociuser"
    "Oracle-Tags.CreatedOn" = "2022-03-21T17:30:34.894Z"
  }
  description = ""
  freeform_tags = {
  }
  name = "oci-github-access"
  notification_config {
    topic_id = oci_ons_notification_topic.export_oci-devops-notification.id
  }
}

